### ISSUE TITLE
add customisable next/previous line functions

### ISSUE THREAD

**Issue by wbolster** [wbolster/emacs-evil-colemak-basics#1]
...for visual-line vs regular line.

**Comment by timacs** [comment]
Since the issue was created, Evil has introduced the [evil-respect-visual-line-mode](https://evil.readthedocs.io/en/latest/settings.html#elispobj-evil-respect-visual-line-mode) setting that allows to customize movements commands in regard to regular and visual lines.

Although there is a [bug in its implementation](https://github.com/emacs-evil/evil/issues/188), I wonder whether you find this option enough to close this issue.

P.S. Thanks for the package! It took me years of using Emacs+Evil+Colemak with dirty hurry-up remappings before I finally allowed time to find a proper solution.

**Comment by wbolster** [comment]
ah thanks, i like no-code solutions 🙃

**Comment by wbolster** [comment]
(and you're welcome. i find it hilarious others think my frankenlayout is _not_ absurd)
